require: rubocop-rails
AllCops:
  Exclude:
    - 'Gemfile'
    - 'Gemfile.lock'
    - 'test/**/*'
    - 'vendor/**/*'
    - 'storage/**/*'
    - 'log/**/*'
    - 'bin/**/*'
    - 'tmp/**/*'
Style/StringLiterals:
  Enabled: false
Layout/IndentationWidth:
  Enabled: false
Layout/MultilineArrayLineBreaks:
  Enabled: true
Layout/MultilineHashKeyLineBreaks:
  Enabled: true
Layout/MultilineMethodArgumentLineBreaks:
  Enabled: true
Style/InlineComment:
  Enabled: true
Style/IpAddresses:
  Enabled: true
Style/StringHashKeys:
  Enabled: true
Metrics/LineLength:
  Enabled: false